# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-14 13:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1_marked', models.BooleanField(default=False)),
                ('category2_marked', models.BooleanField(default=False)),
                ('unprocessed_sentences', models.IntegerField()),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entity_start', models.IntegerField()),
                ('entity_end', models.IntegerField()),
                ('order', models.IntegerField(db_index=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('time', models.IntegerField(null=True)),
                ('marked_category', models.TextField(null=True)),
                ('entity_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.EntityAnnotation')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.Sentence')),
            ],
        ),
    ]
